version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports: [ "5672:5672", "15672:15672" ]
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  # app-producer:
  #   build: .
  #   command: ['node', 'dist/main-producer.js']
  #   environment:
  #     - RABBITMQ_URL=amqp://rabbitmq:5672
  #   depends_on: [rabbitmq]
  # app-worker:
  #   build: .
  #   command: ['node', 'dist/main-worker.js']
  #   environment:
  #     - RABBITMQ_URL=amqp://rabbitmq:5672
  #   depends_on: [rabbitmq]
