version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports: ['5672:5672', '15672:15672']
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  producer:
    build:
      context: .
      dockerfile: apps/producer/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  consumer:
    build:
      context: .
      dockerfile: apps/consumer/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
